# Generated by Django 3.2.4 on 2021-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updationTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updationTime'],
            },
        ),
    ]
