# Generated by Django 3.2.4 on 2021-07-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesAPI', '0002_auto_20210724_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
